// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ZQ8d9m66WpQmuCOj8N33P0FWpaGsz8s',
    appId: '1:701041507507:web:21a83467c7553cab3944c6',
    messagingSenderId: '701041507507',
    projectId: 'betterfy-5bqgih',
    authDomain: 'betterfy-5bqgih.firebaseapp.com',
    storageBucket: 'betterfy-5bqgih.firebasestorage.app',
    measurementId: 'G-25H20022JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyC3ZQ8d9m66WpQmuCOj8N33P0FWpaGsz8s",
      authDomain: "betterfy-5bqgih.firebaseapp.com",
      projectId: "betterfy-5bqgih",
      storageBucket: "betterfy-5bqgih.firebasestorage.app",
      messagingSenderId: "701041507507",
      appId: "1:701041507507:web:21a83467c7553cab3944c6",
      measurementId: "G-25H20022JH"
  );

}